<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-ELMNKHJ9" name="Default test(failed)" tests="2" failures="1" timestamp="9 Oct 2019 02:00:48 GMT" time="0.006" errors="0">
  <testcase name="test2" time="0.0" classname="testNGPriority.TestNGRetryFailedDemo"/>
  <testcase name="test3" time="0.001" classname="testNGPriority.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at testNGPriority.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:20)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test(failed) -->
